"""update kolom shopee

Revision ID: 29685f946e18
Revises: 9c465bd9e72a
Create Date: 2022-07-06 09:20:23.434790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29685f946e18'
down_revision = '9c465bd9e72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabel_shopee_tokped', 'kategori_waktu')
    op.drop_column('tabel_shopee_tokped', 'waktu_new')
    op.drop_column('tabel_shopee_tokped', 'jenis_baru')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabel_shopee_tokped', sa.Column('jenis_baru', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('tabel_shopee_tokped', sa.Column('waktu_new', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('tabel_shopee_tokped', sa.Column('kategori_waktu', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
