"""migrate1

Revision ID: 45cc0d579b6b
Revises: 
Create Date: 2022-07-05 10:21:22.683198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cc0d579b6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('nama_project', sa.String(length=100), nullable=True),
    sa.Column('departemen', sa.String(length=100), nullable=True),
    sa.Column('pic', sa.String(length=100), nullable=True),
    sa.Column('bagian', sa.String(length=100), nullable=True),
    sa.Column('ext', sa.String(length=100), nullable=True),
    sa.Column('deskripsi', sa.String(length=500), nullable=True),
    sa.Column('foto_area', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('history_form_request',
    sa.Column('id_history', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('no_urut_edit', sa.Integer(), nullable=True),
    sa.Column('nama_project', sa.String(length=100), nullable=True),
    sa.Column('departemen', sa.String(length=100), nullable=True),
    sa.Column('pic', sa.String(length=100), nullable=True),
    sa.Column('bagian', sa.String(length=100), nullable=True),
    sa.Column('ext', sa.String(length=20), nullable=True),
    sa.Column('deskripsi', sa.String(length=500), nullable=True),
    sa.Column('foto_area', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id_history')
    )
    op.create_table('m_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roles', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=10), nullable=True),
    sa.Column('nama', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('is_god', sa.Boolean(), nullable=True),
    sa.Column('id_roles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_roles'], ['m_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('m_roles')
    op.drop_table('history_form_request')
    op.drop_table('form_request')
    # ### end Alembic commands ###
