"""migrate2

Revision ID: 55e357815b2d
Revises: 45cc0d579b6b
Create Date: 2022-07-05 10:22:36.332229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55e357815b2d'
down_revision = '45cc0d579b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_request')
    op.drop_table('history_form_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_form_request',
    sa.Column('id_history', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('no_urut_edit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('nama_project', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('departemen', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pic', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bagian', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ext', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('deskripsi', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('foto_area', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('status_aktif', mysql.VARCHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id_history'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('form_request',
    sa.Column('request_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_project', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('departemen', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pic', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bagian', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ext', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('deskripsi', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('foto_area', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('status_aktif', mysql.VARCHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('request_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
