"""migrate tabel shopee tokped

Revision ID: 9c465bd9e72a
Revises: 4fc9b67de55e
Create Date: 2022-07-05 15:51:24.880191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c465bd9e72a'
down_revision = '4fc9b67de55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabel_shopee_tokped',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waktu_pesanan_dibuat', sa.DateTime(), nullable=True),
    sa.Column('status_pesanan', sa.String(length=100), nullable=True),
    sa.Column('nama_produk', sa.String(length=100), nullable=True),
    sa.Column('nomer_referensi_sku', sa.String(length=100), nullable=True),
    sa.Column('harga_awal', sa.Float(precision=15, asdecimal=2), nullable=True),
    sa.Column('jumlah', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('username_pembeli', sa.String(length=100), nullable=True),
    sa.Column('kota_kabupaten', sa.String(length=100), nullable=True),
    sa.Column('provinsi', sa.String(length=100), nullable=True),
    sa.Column('jenis_baru', sa.String(length=100), nullable=True),
    sa.Column('waktu_new', sa.String(length=100), nullable=True),
    sa.Column('kategori_waktu', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabel_shopee_tokped')
    # ### end Alembic commands ###
