"""update kolom shopee 3

Revision ID: dcdc2d1e5a1c
Revises: 29685f946e18
Create Date: 2022-07-06 16:33:04.339662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdc2d1e5a1c'
down_revision = '29685f946e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabel_shopee_tokped', sa.Column('olshop', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabel_shopee_tokped', 'olshop')
    # ### end Alembic commands ###
